//! The runtime's C ABI as a symbol table, for the `velt dev` JIT host (`velt_rt_host` only):
//! generated code resolves `velt_rt_*` calls through it instead of a linker. Generated by
//! build.rs from the `#[no_mangle] extern "C"` functions in these sources.

/// A runtime function's address.
#[derive(Clone, Copy, Debug)]
pub struct AbiAddress(pub *const u8);

// SAFETY: a code address; nothing is read or written through it here.
unsafe impl Sync for AbiAddress {}

include!(concat!(env!("OUT_DIR"), "/abi_symbols.rs"));

/// [`ABI_SYMBOLS`] in the shape `JITBuilder::symbol` takes.
pub fn symbol_table() -> Vec<(&'static str, *const u8)> {
    ABI_SYMBOLS.iter().map(|(name, a)| (*name, a.0)).collect()
}
