//! `velt completions <shell>`: completion scripts for bash, zsh, fish and PowerShell, generated
//! from the help table ([`super::help::COMMANDS`]) so they never drift from the parser. They
//! complete command names, each command's options, the values of `--template`, `--backend` and
//! `--emit`, the shells of `completions`, the commands of `help`, and otherwise files.

use super::help::{command_names, CommandHelp, COMMANDS};
use crate::templates::Template;

/// A shell `velt completions` can generate a script for.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Shell {
    /// GNU bash.
    Bash,
    /// zsh.
    Zsh,
    /// fish.
    Fish,
    /// PowerShell (Windows PowerShell 5 and PowerShell 7+).
    PowerShell,
}

/// Shell names accepted by `velt completions`.
pub const SHELLS: &[&str] = &["bash", "zsh", "fish", "powershell"];

impl Shell {
    /// The shell called `name` (`pwsh` is PowerShell).
    pub fn parse(name: &str) -> Result<Shell, String> {
        match name {
            "bash" => Ok(Shell::Bash),
            "zsh" => Ok(Shell::Zsh),
            "fish" => Ok(Shell::Fish),
            "powershell" | "pwsh" => Ok(Shell::PowerShell),
            other => Err(format!(
                "unknown shell `{other}` (expected bash, zsh, fish or powershell){}",
                super::suggest::hint(other, SHELLS)
            )),
        }
    }
}

/// The completion script for `shell`.
pub fn script(shell: Shell) -> String {
    match shell {
        Shell::Bash => bash(),
        Shell::Zsh => zsh(),
        Shell::Fish => fish(),
        Shell::PowerShell => powershell(),
    }
}

/// Options whose value comes from a fixed list.
fn option_values() -> Vec<(&'static str, Vec<&'static str>)> {
    vec![
        (
            "--template",
            Template::ALL.iter().map(|t| t.name()).collect(),
        ),
        ("--backend", vec!["cranelift", "llvm"]),
        ("--emit", vec!["vir", "llvm", "obj", "exe"]),
    ]
}

/// Words that complete the first argument of a command (instead of files).
fn positional_values(c: &CommandHelp) -> Option<Vec<&'static str>> {
    match c.name {
        "completions" => Some(SHELLS.to_vec()),
        "help" => Some(command_names()),
        "registry" => Some(vec!["serve", "user", "owner"]),
        "owner" => Some(vec!["list", "add", "remove"]),
        _ => None,
    }
}

fn bash() -> String {
    let mut s = format!(
        "# bash completion for velt (generated by `velt completions bash`)\n\
         _velt() {{\n  local cur=\"${{COMP_WORDS[COMP_CWORD]}}\" prev=\"${{COMP_WORDS[COMP_CWORD-1]}}\"\n  \
         local cmd=\"${{COMP_WORDS[1]}}\" opts=\"\"\n  \
         if [[ $COMP_CWORD -eq 1 ]]; then\n    \
         COMPREPLY=($(compgen -W \"{} --help --version\" -- \"$cur\"))\n    return\n  fi\n  case \"$prev\" in\n",
        command_names().join(" ")
    );
    for (flag, values) in option_values() {
        s.push_str(&format!(
            "    {flag}) COMPREPLY=($(compgen -W \"{}\" -- \"$cur\")); return ;;\n",
            values.join(" ")
        ));
    }
    s.push_str("  esac\n  case \"$cmd\" in\n");
    for c in COMMANDS {
        match positional_values(c) {
            Some(values) => s.push_str(&format!(
                "    {}) COMPREPLY=($(compgen -W \"{}\" -- \"$cur\")); return ;;\n",
                c.name,
                values.join(" ")
            )),
            None => s.push_str(&format!(
                "    {}) opts=\"{}\" ;;\n",
                c.name,
                c.flags().join(" ")
            )),
        }
    }
    s.push_str(
        "  esac\n  if [[ \"$cur\" == -* ]]; then\n    COMPREPLY=($(compgen -W \"$opts\" -- \"$cur\"))\n  \
         else\n    COMPREPLY=($(compgen -f -- \"$cur\"))\n  fi\n}\ncomplete -o filenames -F _velt velt\n",
    );
    s
}

/// `text` inside single quotes for zsh/fish/PowerShell.
fn quoted(text: &str, escaped_quote: &str) -> String {
    format!("'{}'", text.replace('\'', escaped_quote))
}

fn zsh() -> String {
    let mut s = String::from(
        "#compdef velt\n# zsh completion for velt (generated by `velt completions zsh`)\n_velt() {\n  local -a commands\n  commands=(\n",
    );
    for c in COMMANDS {
        let item = format!("{}:{}", c.name, c.summary);
        s.push_str(&format!("    {}\n", quoted(&item, "'\\''")));
    }
    s.push_str(
        "  )\n  if (( CURRENT == 2 )); then\n    _describe 'command' commands\n    return\n  fi\n",
    );
    s.push_str("  case $words[CURRENT-1] in\n");
    for (flag, values) in option_values() {
        s.push_str(&format!(
            "    {flag}) compadd -- {}; return ;;\n",
            values.join(" ")
        ));
    }
    s.push_str("  esac\n  if [[ $PREFIX == -* ]]; then\n    case $words[2] in\n");
    for c in COMMANDS {
        s.push_str(&format!(
            "      {}) compadd -- {} ;;\n",
            c.name,
            c.flags().join(" ")
        ));
    }
    s.push_str("    esac\n    return\n  fi\n  case $words[2] in\n");
    for c in COMMANDS {
        if let Some(values) = positional_values(c) {
            s.push_str(&format!(
                "    {}) compadd -- {} ;;\n",
                c.name,
                values.join(" ")
            ));
        }
    }
    s.push_str("    *) _files ;;\n  esac\n}\n_velt \"$@\"\n");
    s
}

/// `-s x` / `-l name` arguments of `complete` for one option label, and whether it takes a value.
fn fish_flag(label: &str) -> (String, bool) {
    let mut args = vec![];
    for word in label.split([' ', ',']).filter(|w| w.starts_with('-')) {
        match word.strip_prefix("--") {
            Some(long) => args.push(format!("-l {long}")),
            None => args.push(format!("-s {}", &word[1..])),
        }
    }
    (args.join(" "), label.contains('<'))
}

fn fish() -> String {
    let mut s = String::from(
        "# fish completion for velt (generated by `velt completions fish`)\ncomplete -c velt -f\n",
    );
    for c in COMMANDS {
        s.push_str(&format!(
            "complete -c velt -n __fish_use_subcommand -a {} -d {}\n",
            c.name,
            quoted(c.summary, "\\'")
        ));
    }
    let values = option_values();
    for c in COMMANDS {
        let cond = format!("-n '__fish_seen_subcommand_from {}'", c.name);
        if let Some(words) = positional_values(c) {
            s.push_str(&format!(
                "complete -c velt {cond} -a '{}'\n",
                words.join(" ")
            ));
        } else if c.name != "new" {
            s.push_str(&format!("complete -c velt {cond} -F\n"));
        }
        for (label, desc) in c.options {
            let (flag, takes_value) = fish_flag(label);
            let listed = values.iter().find(|(v, _)| label.starts_with(v));
            let value = match listed {
                Some((_, words)) => format!(" -x -a '{}'", words.join(" ")),
                None if takes_value => " -r".to_string(),
                None => String::new(),
            };
            s.push_str(&format!(
                "complete -c velt {cond} {flag}{value} -d {}\n",
                quoted(desc, "\\'")
            ));
        }
    }
    s
}

fn powershell() -> String {
    let mut s = String::from(
        "# PowerShell completion for velt (generated by `velt completions powershell`)\n\
         Register-ArgumentCompleter -Native -CommandName velt, velt.exe -ScriptBlock {\n    \
         param($wordToComplete, $commandAst, $cursorPosition)\n    $flags = @{\n",
    );
    for c in COMMANDS {
        let flags: Vec<String> = c.flags().iter().map(|f| format!("'{f}'")).collect();
        s.push_str(&format!("        '{}' = @({})\n", c.name, flags.join(", ")));
    }
    s.push_str("    }\n    $values = @{\n");
    for (flag, words) in option_values() {
        let words: Vec<String> = words.iter().map(|w| format!("'{w}'")).collect();
        s.push_str(&format!("        '{flag}' = @({})\n", words.join(", ")));
    }
    for c in COMMANDS {
        if let Some(words) = positional_values(c) {
            let words: Vec<String> = words.iter().map(|w| format!("'{w}'")).collect();
            s.push_str(&format!("        '{}' = @({})\n", c.name, words.join(", ")));
        }
    }
    s.push_str(
        "    }\n    \
         $words = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })\n    \
         $done = if ($wordToComplete) { $words.Count - 1 } else { $words.Count }\n    \
         $candidates = @()\n    \
         if ($done -le 1) {\n        $candidates = @($flags.Keys) + @('--help', '--version')\n    \
         } elseif ($values.ContainsKey($words[$done - 1])) {\n        $candidates = $values[$words[$done - 1]]\n    \
         } elseif ($wordToComplete -like '-*' -and $flags.ContainsKey($words[1])) {\n        $candidates = $flags[$words[1]]\n    \
         } elseif ($done -eq 2 -and $values.ContainsKey($words[1])) {\n        $candidates = $values[$words[1]]\n    \
         }\n    \
         $candidates | Where-Object { $_ -like \"$wordToComplete*\" } | Sort-Object | ForEach-Object {\n        \
         [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)\n    }\n}\n",
    );
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_shells() {
        assert_eq!(Shell::parse("pwsh"), Ok(Shell::PowerShell));
        assert!(Shell::parse("bsh")
            .unwrap_err()
            .contains("did you mean `bash`?"));
    }

    #[test]
    fn every_script_names_every_command_and_flag() {
        for shell in [Shell::Bash, Shell::Zsh, Shell::Fish, Shell::PowerShell] {
            let text = script(shell);
            for c in COMMANDS {
                assert!(text.contains(c.name), "{shell:?} lacks {}", c.name);
            }
            for word in [
                "websocket",
                "cranelift",
                "--release",
                "--template",
                "powershell",
            ] {
                assert!(text.contains(word), "{shell:?} lacks {word}");
            }
        }
    }

    #[test]
    fn bash_script_shape() {
        let text = script(Shell::Bash);
        assert!(text.contains("complete -o filenames -F _velt velt"));
        assert!(
            text.contains("    --template) COMPREPLY=($(compgen -W \"app cli api websocket lib\"")
        );
        assert!(
            text.contains("    completions) COMPREPLY=($(compgen -W \"bash zsh fish powershell\"")
        );
    }

    #[test]
    fn fish_flags() {
        assert_eq!(
            fish_flag("-o, --output <path>"),
            ("-s o -l output".into(), true)
        );
        assert_eq!(fish_flag("--release"), ("-l release".into(), false));
        let text = script(Shell::Fish);
        assert!(
            text.contains("complete -c velt -n '__fish_seen_subcommand_from new' -l template -x -a 'app cli api websocket lib'"),
            "{text}"
        );
    }

    #[test]
    fn zsh_and_powershell_shapes() {
        assert!(script(Shell::Zsh).starts_with("#compdef velt\n"));
        let ps = script(Shell::PowerShell);
        assert!(ps.contains("Register-ArgumentCompleter -Native -CommandName velt"));
        assert!(ps.contains("'--emit' = @('vir', 'llvm', 'obj', 'exe')"));
    }
}
