[package]
name = "vpm"
version.workspace = true
edition.workspace = true

[dependencies]
object = { version = "0.39", default-features = false, features = ["read", "std"] }
semver = "1.0.28"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
toml = "1.1.6"
velt_common.workspace = true
velt_fmt.workspace = true
velt_http = { path = "../velt_http" }
velt_syntax.workspace = true

[dev-dependencies]
tempfile = "3.27.0"
