//! A reference model of JavaScript string semantics (docs/internals/design/strings.md, #377): a
//! string is a `Vec<u16>` of UTF-16 code units, and each operation follows ECMAScript. The model
//! is checked against tables generated by node (utf16_table.rs); utf16_props.rs checks the runtime
//! against the model.
//!
//! The canonical WTF-8 encoding (lone surrogates as 3-byte sequences, pairs always joined) is here
//! too: it maps the model's strings to the runtime's bytes and back.

/// The JS `ToIntegerOrInfinity` of a position argument, clamped to `0..=len` after counting a
/// negative value from the end (`slice`'s `RelativeIndex`).
fn relative(i: i64, len: usize) -> usize {
    if i < 0 {
        len.saturating_sub(i.unsigned_abs() as usize)
    } else {
        (i as u64).min(len as u64) as usize
    }
}

/// A position argument clamped to `0..=len` (negative is 0): `indexOf`, `lastIndexOf`.
fn clamp(i: i64, len: usize) -> usize {
    (i.max(0) as u64).min(len as u64) as usize
}

/// `s.slice(start, end)`; an omitted `end` is `i64::MAX`, as the prelude passes it.
pub fn slice(s: &[u16], start: i64, end: i64) -> Vec<u16> {
    let (a, b) = (relative(start, s.len()), relative(end, s.len()));
    if a < b {
        s[a..b].to_vec()
    } else {
        Vec::new()
    }
}

/// `s.charCodeAt(i)`; -1 out of range (JS: `NaN`).
pub fn char_code_at(s: &[u16], i: i64) -> i64 {
    usize::try_from(i)
        .ok()
        .and_then(|i| s.get(i))
        .map_or(-1, |&u| u as i64)
}

/// `String.fromCharCode(code)`: `ToUint16`.
pub fn from_char_code(code: i64) -> Vec<u16> {
    vec![code as u16]
}

fn matches_at(s: &[u16], needle: &[u16], k: usize) -> bool {
    s.get(k..k + needle.len()) == Some(needle)
}

/// `s.indexOf(needle, from)`.
pub fn index_of(s: &[u16], needle: &[u16], from: i64) -> i64 {
    let start = clamp(from, s.len());
    if needle.len() > s.len() {
        return -1;
    }
    (start..=s.len() - needle.len())
        .find(|&k| matches_at(s, needle, k))
        .map_or(-1, |k| k as i64)
}

/// `s.lastIndexOf(needle, from)`; an omitted `from` is `i64::MAX`.
pub fn last_index_of(s: &[u16], needle: &[u16], from: i64) -> i64 {
    if needle.len() > s.len() {
        return -1;
    }
    let start = clamp(from, s.len()).min(s.len() - needle.len());
    (0..=start)
        .rev()
        .find(|&k| matches_at(s, needle, k))
        .map_or(-1, |k| k as i64)
}

pub fn includes(s: &[u16], needle: &[u16]) -> bool {
    index_of(s, needle, 0) >= 0
}

pub fn starts_with(s: &[u16], prefix: &[u16]) -> bool {
    s.starts_with(prefix)
}

pub fn ends_with(s: &[u16], suffix: &[u16]) -> bool {
    s.ends_with(suffix)
}

/// `a < b` and friends: code-unit order, as -1 / 0 / 1.
pub fn cmp(a: &[u16], b: &[u16]) -> i32 {
    a.cmp(b) as i32
}

/// `s.split(sep)` (no limit).
pub fn split(s: &[u16], sep: &[u16]) -> Vec<Vec<u16>> {
    if sep.is_empty() {
        return s.iter().map(|&u| vec![u]).collect();
    }
    let mut out = Vec::new();
    let mut last = 0;
    let mut k = 0;
    while k + sep.len() <= s.len() {
        if matches_at(s, sep, k) {
            out.push(s[last..k].to_vec());
            k += sep.len();
            last = k;
        } else {
            k += 1;
        }
    }
    out.push(s[last..].to_vec());
    out
}

/// ECMAScript `GetSubstitution` for a string pattern (no captures): `$$`, `$&`, `` $` `` and `$'`;
/// any other `$` stays as written.
fn substitute(out: &mut Vec<u16>, to: &[u16], s: &[u16], pos: usize, matched: usize) {
    const DOLLAR: u16 = b'$' as u16;
    let mut i = 0;
    while i < to.len() {
        let piece: Option<&[u16]> = match to.get(i + 1) {
            _ if to[i] != DOLLAR => None,
            Some(&DOLLAR) => Some(&[DOLLAR]),
            Some(0x26) => Some(&s[pos..pos + matched]), // $&
            Some(0x60) => Some(&s[..pos]),              // $`
            Some(0x27) => Some(&s[pos + matched..]),    // $'
            _ => None,
        };
        match piece {
            Some(p) => {
                out.extend_from_slice(p);
                i += 2;
            }
            None => {
                out.push(to[i]);
                i += 1;
            }
        }
    }
}

fn replace_at(s: &[u16], from: &[u16], to: &[u16], positions: &[usize]) -> Vec<u16> {
    let mut out = Vec::new();
    let mut copied = 0;
    for &pos in positions {
        out.extend_from_slice(&s[copied..pos]);
        substitute(&mut out, to, s, pos, from.len());
        copied = pos + from.len();
    }
    out.extend_from_slice(&s[copied..]);
    out
}

/// `s.replace(from, to)`: the first occurrence.
pub fn replace(s: &[u16], from: &[u16], to: &[u16]) -> Vec<u16> {
    let k = index_of(s, from, 0);
    let positions: Vec<usize> = if k < 0 { vec![] } else { vec![k as usize] };
    replace_at(s, from, to, &positions)
}

/// `s.replaceAll(from, to)`: every non-overlapping occurrence; an empty `from` matches between
/// every two code units and at both ends.
pub fn replace_all(s: &[u16], from: &[u16], to: &[u16]) -> Vec<u16> {
    let mut positions = Vec::new();
    let mut k = index_of(s, from, 0);
    while k >= 0 {
        positions.push(k as usize);
        let next = k as usize + from.len().max(1);
        if next > s.len() {
            break;
        }
        k = index_of(s, from, next as i64);
    }
    replace_at(s, from, to, &positions)
}

/// `s.repeat(n)`; `None` is a `RangeError` (negative count).
pub fn repeat(s: &[u16], n: i64) -> Option<Vec<u16>> {
    usize::try_from(n).ok().map(|n| s.repeat(n))
}

/// The fill of `padStart`/`padEnd`: `fill` repeated and cut to `target - len` code units (the
/// cut may split a pair).
fn padding(s: &[u16], target: i64, fill: &[u16]) -> Vec<u16> {
    let want = usize::try_from(target).unwrap_or(0).saturating_sub(s.len());
    fill.iter()
        .copied()
        .cycle()
        .take(if fill.is_empty() { 0 } else { want })
        .collect()
}

pub fn pad_start(s: &[u16], target: i64, fill: &[u16]) -> Vec<u16> {
    let mut out = padding(s, target, fill);
    out.extend_from_slice(s);
    out
}

pub fn pad_end(s: &[u16], target: i64, fill: &[u16]) -> Vec<u16> {
    let mut out = s.to_vec();
    out.extend(padding(s, target, fill));
    out
}

pub fn is_high(u: u16) -> bool {
    (0xD800..0xDC00).contains(&u)
}

pub fn is_low(u: u16) -> bool {
    (0xDC00..0xE000).contains(&u)
}

/// Canonical WTF-8: a pair becomes its 4-byte code point; a lone surrogate becomes its 3-byte
/// encoding.
pub fn wtf8_encode(s: &[u16]) -> Vec<u8> {
    let mut out = Vec::with_capacity(s.len());
    let mut i = 0;
    while i < s.len() {
        let u = s[i] as u32;
        let cp = match s.get(i + 1) {
            Some(&lo) if is_high(s[i]) && is_low(lo) => {
                i += 1;
                0x10000 + ((u - 0xD800) << 10) + (lo as u32 - 0xDC00)
            }
            _ => u,
        };
        i += 1;
        match cp {
            0..=0x7F => out.push(cp as u8),
            0x80..=0x7FF => out.extend([0xC0 | (cp >> 6) as u8, 0x80 | (cp & 0x3F) as u8]),
            0x800..=0xFFFF => out.extend([
                0xE0 | (cp >> 12) as u8,
                0x80 | ((cp >> 6) & 0x3F) as u8,
                0x80 | (cp & 0x3F) as u8,
            ]),
            _ => out.extend([
                0xF0 | (cp >> 18) as u8,
                0x80 | ((cp >> 12) & 0x3F) as u8,
                0x80 | ((cp >> 6) & 0x3F) as u8,
                0x80 | (cp & 0x3F) as u8,
            ]),
        }
    }
    out
}

/// The code units of WTF-8 bytes. Panics on bytes that aren't WTF-8, or that encode a pair as
/// two 3-byte halves (not canonical): the runtime must never produce either.
pub fn wtf8_decode(b: &[u8]) -> Vec<u16> {
    let mut out = Vec::with_capacity(b.len());
    let mut i = 0;
    while i < b.len() {
        let lead = b[i];
        let n = match lead {
            0x00..=0x7F => 1,
            0xC2..=0xDF => 2,
            0xE0..=0xEF => 3,
            0xF0..=0xF4 => 4,
            _ => panic!("not WTF-8: lead byte {lead:#x} at {i} in {b:x?}"),
        };
        let seq = b
            .get(i..i + n)
            .unwrap_or_else(|| panic!("not WTF-8: truncated at {i} in {b:x?}"));
        assert!(
            seq[1..].iter().all(|&c| c & 0xC0 == 0x80),
            "not WTF-8: continuation at {i} in {b:x?}"
        );
        let cp = match n {
            1 => lead as u32,
            2 => ((lead as u32 & 0x1F) << 6) | (seq[1] as u32 & 0x3F),
            3 => {
                ((lead as u32 & 0x0F) << 12)
                    | ((seq[1] as u32 & 0x3F) << 6)
                    | (seq[2] as u32 & 0x3F)
            }
            _ => {
                ((lead as u32 & 0x07) << 18)
                    | ((seq[1] as u32 & 0x3F) << 12)
                    | ((seq[2] as u32 & 0x3F) << 6)
                    | (seq[3] as u32 & 0x3F)
            }
        };
        let shortest = match n {
            1 => true,
            2 => cp >= 0x80,
            3 => cp >= 0x800,
            _ => (0x10000..=0x10FFFF).contains(&cp),
        };
        assert!(
            shortest,
            "not WTF-8: overlong or out of range at {i} in {b:x?}"
        );
        if cp >= 0x10000 {
            out.push((0xD800 + ((cp - 0x10000) >> 10)) as u16);
            out.push((0xDC00 + ((cp - 0x10000) & 0x3FF)) as u16);
        } else {
            let u = cp as u16;
            assert!(
                !(is_low(u) && out.last().is_some_and(|&p| is_high(p))),
                "not canonical WTF-8: a pair stored as two halves at {i} in {b:x?}"
            );
            out.push(u);
        }
        i += n;
    }
    out
}

/// A string for assertion messages: printable ASCII as is, everything else as `\uXXXX`.
pub fn show(s: &[u16]) -> String {
    let mut o = String::from("\"");
    for &u in s {
        match u {
            0x22 => o.push_str("\\\""),
            0x5C => o.push_str("\\\\"),
            0x20..=0x7E => o.push(u as u8 as char),
            _ => o.push_str(&format!("\\u{u:04X}")),
        }
    }
    o.push('"');
    o
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::abi_tests::utf16_table as js;

    fn split_flat(parts: &[Vec<u16>]) -> Vec<&[u16]> {
        parts.iter().map(Vec::as_slice).collect()
    }

    #[test]
    fn model_matches_node() {
        let t = |i: usize| js::STRS[i];
        for &(s, a, b, want) in js::SLICE {
            assert_eq!(slice(t(s), a, b), want, "{}.slice({a}, {b})", show(t(s)));
        }
        for &(s, want) in js::CHAR_CODE_AT {
            for (&i, &want) in js::CHAR_CODE_AT_INDEXES.iter().zip(&want) {
                assert_eq!(
                    char_code_at(t(s), i),
                    want,
                    "{}.charCodeAt({i})",
                    show(t(s))
                );
            }
        }
        for &(code, want) in js::FROM_CHAR_CODE {
            assert_eq!(from_char_code(code), [want], "String.fromCharCode({code})");
        }
        for &(s, n, idx, last, inc, starts, ends) in js::SEARCH {
            let (s, n) = (t(s), t(n));
            let m = format!("{} {}", show(s), show(n));
            for (&from, &want) in js::INDEX_OF_FROMS.iter().zip(&idx) {
                assert_eq!(index_of(s, n, from), want, "indexOf from {from}: {m}");
            }
            for (&from, &want) in js::LAST_INDEX_OF_FROMS.iter().zip(&last) {
                assert_eq!(
                    last_index_of(s, n, from),
                    want,
                    "lastIndexOf from {from}: {m}"
                );
            }
            assert_eq!(includes(s, n), inc, "includes {m}");
            assert_eq!(starts_with(s, n), starts, "startsWith {m}");
            assert_eq!(ends_with(s, n), ends, "endsWith {m}");
        }
        for &(a, want) in js::CMP {
            for (b, &want) in want.iter().enumerate() {
                assert_eq!(cmp(t(a), t(b)), want, "{} vs {}", show(t(a)), show(t(b)));
            }
        }
        for &(s, sep, want) in js::SPLIT {
            let got = split(t(s), t(sep));
            assert_eq!(
                split_flat(&got),
                want,
                "{}.split({})",
                show(t(s)),
                show(t(sep))
            );
        }
        for &(s, from, to, once, all) in js::REPLACE {
            let (s, from, to) = (t(s), t(from), t(to));
            let m = format!("{}, {}, {}", show(s), show(from), show(to));
            assert_eq!(replace(s, from, to), once, "replace {m}");
            assert_eq!(replace_all(s, from, to), all, "replaceAll {m}");
        }
        for &(s, n, ok, want) in js::REPEAT {
            let want = ok.then_some(want);
            assert_eq!(
                repeat(t(s), n).as_deref(),
                want,
                "{}.repeat({n})",
                show(t(s))
            );
        }
        for &(s, target, fill, start, end) in js::PAD {
            let (s, fill) = (t(s), t(fill));
            let m = format!("{}, {target}, {}", show(s), show(fill));
            assert_eq!(pad_start(s, target, fill), start, "padStart {m}");
            assert_eq!(pad_end(s, target, fill), end, "padEnd {m}");
        }
    }

    #[test]
    fn wtf8_encodes_canonically() {
        for &(s, want) in js::WTF8 {
            let s = js::STRS[s];
            assert_eq!(wtf8_encode(s), want, "{}", show(s));
            assert_eq!(wtf8_decode(want), s, "{}", show(s));
        }
        // Lone surrogates take their 3-byte encoding.
        assert_eq!(wtf8_encode(&[0xD83D]), [0xED, 0xA0, 0xBD]);
        assert_eq!(wtf8_encode(&[0x61, 0xDE00]), [0x61, 0xED, 0xB8, 0x80]);
        assert_eq!(
            wtf8_encode(&[0xDE00, 0xD83D]),
            [0xED, 0xB8, 0x80, 0xED, 0xA0, 0xBD]
        );
        // Gluing the halves of a pair back together gives the pair's 4-byte encoding.
        let halves = [wtf8_encode(&[0xD83D]), wtf8_encode(&[0xDE00])].concat();
        assert_ne!(halves, wtf8_encode(&[0xD83D, 0xDE00]));
        assert_eq!(
            wtf8_encode(&wtf8_decode(&wtf8_encode(&[0xD83D, 0xDE00]))),
            [0xF0, 0x9F, 0x98, 0x80]
        );
    }

    #[test]
    #[should_panic(expected = "not canonical WTF-8")]
    fn wtf8_decode_rejects_split_pairs() {
        wtf8_decode(&[0xED, 0xA0, 0xBD, 0xED, 0xB8, 0x80]);
    }
}
