// Generates crates/velt_rt/tests/abi/js_table.rs from a real JS engine (node):`n//   node crates/velt_rt/scripts/gen_str_table.js > crates/velt_rt/tests/abi/js_table.rs
const MAX = "i64::MAX";
function rs(s) {
  let o = '"';
  for (const ch of s) {
    const c = ch.codePointAt(0);
    if (ch === '"') o += '\\"';
    else if (ch === "\\") o += "\\\\";
    else if (c >= 0x20 && c < 0x7f) o += ch;
    else o += "\\u{" + c.toString(16) + "}";
  }
  return o + '"';
}
const dv = new DataView(new ArrayBuffer(8));
function f(x) {
  if (Number.isNaN(x)) return "NAN";
  dv.setFloat64(0, x);
  return "0x" + dv.getBigUint64(0).toString(16).padStart(16, "0");
}
function i(x) { return x === MAX ? MAX : String(x); }
const out = [];
out.push("//! Expected results generated by a real JS engine (node 22) with");
out.push("//! crates/velt_rt/scripts/gen_str_table.js (then `cargo fmt`); regenerate instead of editing.");
out.push("//! Floats are bit patterns (`NAN` = any NaN). String inputs of index-based cases are ASCII,");
out.push("//! where byte offsets and UTF-16 indexes agree.");
out.push("");
out.push("pub const NAN: u64 = u64::MAX;");
function table(name, ty, rows) {
  out.push(`pub const ${name}: &[${ty}] = &[`);
  for (const r of rows) out.push(`    (${r.join(", ")}),`);
  out.push("];");
}

const intInputs = ["", " 42", "42px", "-42", "+42", "0x1F", "0X1f", "-0x1F", "0x", "  \n\t 12", "  7",
  "﻿9", "\u0085 5", "᠎5", "3.14", "1e3", "abc", "-0", "0", "00012", "9007199254740993",
  "123456789012345678901234567890", "ff", "zz", "Infinity", "1_000", "٣", "0b101", "0o17", "-", "+",
  "--1", "0x" + "f".repeat(40), "1".repeat(70), "10".repeat(40) + "1", "z".repeat(12), "Z9", "7fffffffffffffff",
  "1" + "0".repeat(400), "0x1" + "0".repeat(13) + "08", "0x1" + "0".repeat(13) + "18", "0x1" + "0".repeat(13) + "0801"];
const radixes = [0, 2, 8, 10, 16, 36, 1, 37, -1, 4294967312];
const intRows = [];
for (const s of intInputs) for (const r of radixes) {
  const v = parseInt(s, r === 0 ? undefined : r);
  // V8 is not correctly rounded above 2^53 for radixes other than 10 and powers of two (velt_rt
  // is, below 2^128): those cases are not comparable.
  const exactRadix = [0, 2, 8, 10, 16, 4294967312].includes(r);
  if (!exactRadix && Math.abs(v) >= 2 ** 53) continue;
  intRows.push([rs(s), String(r), f(v)]);
}
table("PARSE_INT", "(&str, i64, u64)", intRows);

const floatInputs = ["3.14", "  3.14abc", "-.5", ".5", "5.", ".", "-", "+", "1e", "1e+", "1e5x", "1E-3", "Infinity",
  "-Infinityx", "+Infinity", "infinity", "0x10", "", "  ", "1.7976931348623159e308", "2e-324", "-0", "0.1e-5",
  "1.2.3", "  4", "12_3", "NaN", "1e1000", "00.5", "0x1F", "0o17", "0b101", "0b", "-0x10", " 12 ", "12 px",
  "\n", "-Infinity", " +Infinity ", "+.5", "0X1f", "1_0", "١", "0.0000001", "1e-7",
  "    42 ﻿", "0x" + "f".repeat(30), "0b" + "1".repeat(60), "0o777", "0o8", "1e+5", "-1e-5",
  "123456789012345678901234567890", "0.1", "9007199254740993", ".e1", "1.e1", "Infinityx", "  -  5",
  "4.9406564584124654e-324", "2.4703282292062327e-324", "\u0085 1"];
table("PARSE_FLOAT", "(&str, u64)", floatInputs.map(s => [rs(s), f(parseFloat(s))]));
table("TO_NUMBER", "(&str, u64)", floatInputs.map(s => [rs(s), f(Number(s))]));

const sl = "hello world";
const slicePairs = [[0, 5], [6, MAX], [-5, MAX], [-5, -1], [3, 1], [-100, 3], [2, 100], [0, 0], [11, MAX],
  [-1, MAX], [0, -100], [5, 5], [-3, -5], [0, MAX], [100, MAX]];
table("SLICE", "(&str, i64, i64, &str)", slicePairs.map(([a, b]) =>
  [rs(sl), i(a), i(b), rs(b === MAX ? sl.slice(a) : sl.slice(a, b))]));

const hay = "abcabc ab";
const needles = ["", "a", "bc", "abc", "x", "c ab", "abcabc ab!", "b"];
const froms = [-5, 0, 1, 3, 4, 9, 10, 100];
const idx = [], lidx = [];
for (const n of needles) {
  for (const fr of froms) idx.push([rs(hay), rs(n), i(fr), String(hay.indexOf(n, fr))]);
  for (const fr of [...froms, MAX]) lidx.push([rs(hay), rs(n), i(fr),
    String(fr === MAX ? hay.lastIndexOf(n) : hay.lastIndexOf(n, fr))]);
}
table("INDEX_OF", "(&str, &str, i64, i64)", idx);
table("LAST_INDEX_OF", "(&str, &str, i64, i64)", lidx);

const pairs = [["abc", ""], ["abc", "a"], ["abc", "c"], ["abc", "abc"], ["abc", "abcd"], ["", ""], ["", "a"],
  ["héllo", "é"], ["héllo", "llo"], ["héllo", "hé"], ["aXbXc", "X"], ["ab", "ba"]];
table("CONTAINS", "(&str, &str, bool, bool, bool)", pairs.map(([s, n]) =>
  [rs(s), rs(n), String(s.includes(n)), String(s.startsWith(n)), String(s.endsWith(n))]));

const splits = [["a,b,,c,", ","], ["", ","], ["", ""], ["abc", ""], ["héllo", ""], ["a--b--c", "--"],
  ["abc", "abc"], ["abc", "x"], ["aaa", "aa"], [",", ","], ["a b  c", " "], ["xéyéz", "é"]];
table("SPLIT", "(&str, &str, &[&str])", splits.map(([s, p]) =>
  [rs(s), rs(p), "&[" + s.split(p).map(rs).join(", ") + "]"]));

const ws = ["  x  ", "\t\n\u000b\f\r         　﻿x y﻿",
  "\u0085x\u0085", "", "   ", "᠎x", "x", " é "];
table("TRIM", "(&str, &str, &str, &str)", ws.map(s => [rs(s), rs(s.trim()), rs(s.trimStart()), rs(s.trimEnd())]));

const cases = ["hello", "Straße", "ǅ", "ΑΣ ΟΔΟΣ", "İstanbul", "ﬁ", "ŉ", "ΐ", "Σ", "aΣ", "ÀÉÎ", "ǆ",
  "MiXeD 123", "", "ὈΔΥΣΣΕΎΣ", "ǰ", "Ωmega", "ß"];
table("CASE", "(&str, &str, &str)", cases.map(s => [rs(s), rs(s.toUpperCase()), rs(s.toLowerCase())]));

const reps = [["aXbXc", "X", "-"], ["abc", "", "-"], ["abc", "b", "[$&]"], ["abc", "b", "$`"], ["abc", "b", "$'"],
  ["abc", "b", "$$"], ["abc", "b", "$1"], ["abc", "b", "$<n>"], ["abc", "x", "y"], ["aaa", "aa", "b"],
  ["", "", "x"], ["abc", "b", "$"], ["héé", "é", "e"], ["a.b.c", ".", "$'$`"], ["xx", "x", "$&$&"], ["héllo", "", "_"]];
table("REPLACE", "(&str, &str, &str, &str, &str)", reps.map(([s, a, b]) =>
  [rs(s), rs(a), rs(b), rs(s.replace(a, b)), rs(s.replaceAll(a, b))]));

const repeats = [["ab", 0], ["ab", 3], ["", 5], ["x", 1], ["é", 2]];
table("REPEAT", "(&str, i64, &str)", repeats.map(([s, n]) => [rs(s), String(n), rs(s.repeat(n))]));

const pads = [["5", 3, "0"], ["abc", 2, "x"], ["abc", 10, "12345"], ["abc", 6, ""], ["abc", 8, "xy"], ["", 3, "ab"],
  ["abc", -1, "x"], ["abc", 4, " "], ["42", 5, "0"]];
table("PAD", "(&str, i64, &str, &str, &str)", pads.map(([s, n, p]) =>
  [rs(s), String(n), rs(p), rs(s.padStart(n, p)), rs(s.padEnd(n, p))]));

table("CHAR_CODE_AT", "(&str, i64, i64)", [-1, 0, 1, 2, 3].map(k => {
  const c = "Az~".charCodeAt(k);
  return [rs("Az~"), String(k), String(Number.isNaN(c) ? -1 : c)];
}));

const codes = [65, 0, 127, 128, 233, 0x20ac, 0xd800, 0xdc00, 65601, -1, 0xfffd, 65536 + 65, 4294967296 + 97];
table("FROM_CHAR_CODE", "(i64, &str)", codes.map(c => [String(c), rs(String.fromCharCode(c).toWellFormed())]));

process.stdout.write(out.join("\n") + "\n");
