// Generates crates/velt_rt/tests/abi/utf16_table.rs from a real JS engine (node), the expected
// results for the UTF-16 reference model (tests/abi/utf16_model.rs, issue #377):
//   node crates/velt_rt/scripts/gen_utf16_table.js > crates/velt_rt/tests/abi/utf16_table.rs
// then `cargo fmt`. Strings are arrays of UTF-16 code units; `i64::MAX` is an omitted argument.
const MAX = "i64::MAX";
const units = (s) => "&[" + Array.from({ length: s.length }, (_, k) => String(s.charCodeAt(k))).join(", ") + "]";
const num = (x) => (x === MAX ? MAX : String(x));
const opt = (x) => (x === MAX ? undefined : x);

// Every input string, referred to by its index in `STRS`.
const pool = [];
const id = (s) => {
  if (!pool.includes(s)) pool.push(s);
  return String(pool.indexOf(s));
};
const strs = ["", "abc", "héllo", "Zoë", "日本語", "a😀b", "ab😀cd😀", "\uD83D", "\uDE00",
  "x\uD83Dy", "\uDE00\uD83D", "a😀\uD83D", "\uFF5E", "\u{10000}", "\uDC00", "é,😀,,\uD83D"];
const needles = ["", "a", "é", "😀", "\uD83D", "\uDE00", "\uDE00b", "a\uD83D", "😀😀", ","];
strs.forEach(id);

const out = [];
out.push("//! Expected results generated by a real JS engine (node 22) with");
out.push("//! crates/velt_rt/scripts/gen_utf16_table.js (then `cargo fmt`); regenerate instead of editing.");
out.push("//! Strings are UTF-16 code units. Inputs are indexes into `STRS`; `i64::MAX` stands for an");
out.push("//! omitted argument.");
out.push("");
const tables = ["/// A string as UTF-16 code units.", "pub type Units = &'static [u16];", ""];
function table(name, ty, rows) {
  tables.push(`pub const ${name}: &[${ty}] = &[`);
  for (const r of rows) tables.push(`    (${r.join(", ")}),`);
  tables.push("];");
}

const sliceRows = [];
for (const s of strs) for (const [a, b] of [[0, 1], [1, 2], [1, MAX], [-1, MAX], [-2, -1], [2, 1], [-100, 3], [3, 100]]) {
  sliceRows.push([id(s), num(a), num(b), units(s.slice(a, opt(b)))]);
}
table("SLICE", "(usize, i64, i64, Units)", sliceRows);

const ccRows = [];
for (const s of strs) for (const i of [-1, 0, 1, 2, 3]) {
  const c = s.charCodeAt(i);
  ccRows.push([id(s), String(i), Number.isNaN(c) ? "-1" : String(c)]);
}
table("CHAR_CODE_AT", "(usize, i64, i64)", ccRows);

table("FROM_CHAR_CODE", "(i64, u16)", [0x41, 0xe9, 0xd83d, 0xde00, 0x1f600, -1, 65536 + 65, 0xffff, 0]
  .map((c) => [String(c), "0x" + String.fromCharCode(c).charCodeAt(0).toString(16)]));

const idx = [], lidx = [], search = [];
for (const s of strs) for (const n of needles) {
  for (const fr of [0, 1, 3, 100]) idx.push([id(s), id(n), num(fr), String(s.indexOf(n, fr))]);
  for (const fr of [-1, 1, 3, MAX]) lidx.push([id(s), id(n), num(fr), String(s.lastIndexOf(n, opt(fr)))]);
  search.push([id(s), id(n), String(s.includes(n)), String(s.startsWith(n)), String(s.endsWith(n))]);
}
table("INDEX_OF", "(usize, usize, i64, i64)", idx);
table("LAST_INDEX_OF", "(usize, usize, i64, i64)", lidx);
table("SEARCH", "(usize, usize, bool, bool, bool)", search);

const cmpRows = [];
for (const a of strs) for (const b of strs) cmpRows.push([id(a), id(b), a < b ? "-1" : a > b ? "1" : "0"]);
table("CMP", "(usize, usize, i32)", cmpRows);

const splitRows = [];
for (const s of strs) for (const sep of ["", ",", "😀", "\uD83D", "\uDE00"]) {
  splitRows.push([id(s), id(sep), "&[" + s.split(sep).map(units).join(", ") + "]"]);
}
table("SPLIT", "(usize, usize, &[Units])", splitRows);

const repRows = [];
for (const s of strs) for (const from of ["", "a", "😀", "\uD83D", "\uDE00"]) {
  for (const to of ["$&|$`|$'", "$$$1", "\uDE00"]) {
    repRows.push([id(s), id(from), id(to), units(s.replace(from, to)), units(s.replaceAll(from, to))]);
  }
}
table("REPLACE", "(usize, usize, usize, Units, Units)", repRows);

// (s, n, ok, result): `ok` false is a RangeError.
const repeatRows = [];
for (const s of strs) for (const n of [-1, 0, 3]) {
  let r = null;
  try { r = s.repeat(n); } catch (e) { if (!(e instanceof RangeError)) throw e; }
  repeatRows.push([id(s), String(n), String(r !== null), units(r ?? "")]);
}
table("REPEAT", "(usize, i64, bool, Units)", repeatRows);

const padRows = [];
for (const s of ["", "abc", "é", "😀", "\uDE00"]) for (const target of [-1, 2, 3, 6]) {
  for (const fill of [" ", "😀", "", "x😀"]) {
    padRows.push([id(s), String(target), id(fill), units(s.padStart(target, fill)), units(s.padEnd(target, fill))]);
  }
}
table("PAD", "(usize, i64, usize, Units, Units)", padRows);

// UTF-8 of the well-formed strings, from node's encoder (WTF-8 agrees with UTF-8 on them).
const encoder = new TextEncoder();
table("WTF8", "(usize, &[u8])", strs.filter((s) => s.isWellFormed()).map((s) =>
  [id(s), "&[" + Array.from(encoder.encode(s), (b) => "0x" + b.toString(16)).join(", ") + "]"]));

out.push("pub const STRS: &[Units] = &[");
for (const s of pool) out.push(`    ${units(s)},`);
out.push("];");
out.push(...tables);
console.log(out.join("\n"));
