// Generates crates/velt_rt/tests/abi/utf16_table.rs from a real JS engine (node), the expected
// results for the UTF-16 reference model (tests/abi/utf16_model.rs, issue #377):
//   node crates/velt_rt/scripts/gen_utf16_table.js > crates/velt_rt/tests/abi/utf16_table.rs
// Strings are arrays of UTF-16 code units; `i64::MAX` is an omitted argument. The output is
// left as generated (one row per line): tests/abi/mod.rs keeps rustfmt off it.
const MAX = "i64::MAX";
const units = (s) => "&[" + Array.from({ length: s.length }, (_, k) => String(s.charCodeAt(k))).join(", ") + "]";
const num = (x) => (x === MAX ? MAX : String(x));
const opt = (x) => (x === MAX ? undefined : x);

// Every input string, referred to by its index in `STRS`.
const pool = [];
const id = (s) => {
  if (!pool.includes(s)) pool.push(s);
  return String(pool.indexOf(s));
};
const strs = ["", "abc", "héllo", "Zoë", "日本語", "a😀b", "ab😀cd😀", "\uD83D", "\uDE00",
  "x\uD83Dy", "\uDE00\uD83D", "a😀\uD83D", "\uFF5E", "\u{10000}", "\uDC00", "é,😀,,\uD83D"];
const needles = ["", "a", "é", "😀", "\uD83D", "\uDE00", "\uDE00b", "a\uD83D", "😀😀", ","];
strs.forEach(id);

const out = [];
out.push("//! Expected results generated by a real JS engine (node 22) with");
out.push("//! crates/velt_rt/scripts/gen_utf16_table.js; regenerate instead of editing.");
out.push("//! Strings are UTF-16 code units. Inputs are indexes into `STRS`; `i64::MAX` stands for an");
out.push("//! omitted argument. One row per line: `mod.rs` keeps rustfmt off this file.");
out.push("");
const tables = ["/// A string as UTF-16 code units.", "pub type Units = &'static [u16];", ""];
function table(name, ty, rows) {
  tables.push(`pub const ${name}: &[${ty}] = &[`);
  for (const r of rows) tables.push(`    (${r.join(", ")}),`);
  tables.push("];");
}

const sliceRows = [];
for (const s of strs) for (const [a, b] of [[0, 1], [1, 2], [1, MAX], [-1, MAX], [-2, -1], [2, 1], [-100, 3], [3, 100]]) {
  sliceRows.push([id(s), num(a), num(b), units(s.slice(a, opt(b)))]);
}
table("SLICE", "(usize, i64, i64, Units)", sliceRows);

const ccIndexes = [-1, 0, 1, 2, 3];
tables.push(`pub const CHAR_CODE_AT_INDEXES: [i64; ${ccIndexes.length}] = [${ccIndexes.join(", ")}];`);
// (s, charCodeAt at each of CHAR_CODE_AT_INDEXES)
table("CHAR_CODE_AT", `(usize, [i64; ${ccIndexes.length}])`, strs.map((s) => [id(s), "[" + ccIndexes.map((i) => {
  const c = s.charCodeAt(i);
  return Number.isNaN(c) ? "-1" : String(c);
}).join(", ") + "]"]));

table("FROM_CHAR_CODE", "(i64, u16)", [0x41, 0xe9, 0xd83d, 0xde00, 0x1f600, -1, 65536 + 65, 0xffff, 0]
  .map((c) => [String(c), "0x" + String.fromCharCode(c).charCodeAt(0).toString(16)]));

const froms = [0, 1, 3, 100], lastFroms = [-1, 1, 3, MAX];
tables.push(`pub const INDEX_OF_FROMS: [i64; ${froms.length}] = [${froms.join(", ")}];`);
tables.push(`pub const LAST_INDEX_OF_FROMS: [i64; ${lastFroms.length}] = [${lastFroms.join(", ")}];`);
// (s, needle, indexOf at each of INDEX_OF_FROMS, lastIndexOf at each of LAST_INDEX_OF_FROMS,
//  includes, startsWith, endsWith)
const search = [];
for (const s of strs) for (const n of needles) {
  search.push([id(s), id(n), "[" + froms.map((fr) => s.indexOf(n, fr)).join(", ") + "]",
    "[" + lastFroms.map((fr) => s.lastIndexOf(n, opt(fr))).join(", ") + "]",
    String(s.includes(n)), String(s.startsWith(n)), String(s.endsWith(n))]);
}
tables.push("/// (s, needle, `indexOf` from each of `INDEX_OF_FROMS`, `lastIndexOf` from each of");
tables.push("/// `LAST_INDEX_OF_FROMS`, `includes`, `startsWith`, `endsWith`)");
tables.push(`pub type SearchRow = (usize, usize, [i64; ${froms.length}], [i64; ${lastFroms.length}], bool, bool, bool);`);
table("SEARCH", "SearchRow", search);

// (a, the order of `a` against each of the first STRS.len() strings, as -1 / 0 / 1)
table("CMP", `(usize, [i32; ${strs.length}])`, strs.map((a) =>
  [id(a), "[" + strs.map((b) => (a < b ? "-1" : a > b ? "1" : "0")).join(", ") + "]"]));

const splitRows = [];
for (const s of strs) for (const sep of ["", ",", "😀", "\uD83D", "\uDE00"]) {
  splitRows.push([id(s), id(sep), "&[" + s.split(sep).map(units).join(", ") + "]"]);
}
table("SPLIT", "(usize, usize, &[Units])", splitRows);

const repRows = [];
for (const s of strs) for (const from of ["", "a", "😀", "\uD83D", "\uDE00"]) {
  for (const to of ["$&|$`|$'", "$$$1", "\uDE00"]) {
    repRows.push([id(s), id(from), id(to), units(s.replace(from, to)), units(s.replaceAll(from, to))]);
  }
}
table("REPLACE", "(usize, usize, usize, Units, Units)", repRows);

// (s, n, ok, result): `ok` false is a RangeError.
const repeatRows = [];
for (const s of strs) for (const n of [-1, 0, 3]) {
  let r = null;
  try { r = s.repeat(n); } catch (e) { if (!(e instanceof RangeError)) throw e; }
  repeatRows.push([id(s), String(n), String(r !== null), units(r ?? "")]);
}
table("REPEAT", "(usize, i64, bool, Units)", repeatRows);

const padRows = [];
for (const s of ["", "abc", "é", "😀", "\uDE00"]) for (const target of [-1, 2, 3, 6]) {
  for (const fill of [" ", "😀", "", "x😀"]) {
    padRows.push([id(s), String(target), id(fill), units(s.padStart(target, fill)), units(s.padEnd(target, fill))]);
  }
}
table("PAD", "(usize, i64, usize, Units, Units)", padRows);

// UTF-8 of the well-formed strings, from node's encoder (WTF-8 agrees with UTF-8 on them).
const encoder = new TextEncoder();
table("WTF8", "(usize, &[u8])", strs.filter((s) => s.isWellFormed()).map((s) =>
  [id(s), "&[" + Array.from(encoder.encode(s), (b) => "0x" + b.toString(16)).join(", ") + "]"]));

out.push("pub const STRS: &[Units] = &[");
for (const s of pool) out.push(`    ${units(s)},`);
out.push("];");
out.push(...tables);
console.log(out.join("\n"));
