//! Module IR: header, statics (see `statics`), extern declarations, defined functions, the
//! intrinsics they use, and attribute groups. A module holds the whole program, or one codegen
//! unit of it (see `units`).

use std::collections::{BTreeSet, HashSet};
use std::fmt::Write;

use velt_vir::vir::{self, Linkage};

use crate::debug::DebugInfo;
use crate::function::emit_function;
use crate::runtime::{self, Allocator, Effects};
use crate::statics::static_data;
use crate::statics::StaticDefinition;
use crate::target::Target;
use crate::types::{abi_ret, abi_type, global_name, validate_aggregates};
use crate::units::{Shared, Unit};
use crate::CodegenResult;

/// Attribute group of defined functions.
pub(crate) const FN_ATTRS: &str = "#0";
/// Attribute group of ordinary externs (C functions and the Rust runtime do not unwind into
/// Velt code: Rust `extern "C"` aborts on panic).
const EXTERN_ATTRS: &str = "#1";
/// Attribute group of noreturn externs.
const NORETURN_ATTRS: &str = "#2";
/// Attribute group of runtime functions that touch no memory (see `runtime`).
const PURE_ATTRS: &str = "#3";
/// Attribute group of runtime functions that only read memory.
const READONLY_ATTRS: &str = "#4";
/// Attribute group of runtime functions that read memory and update private caches.
const READ_CACHING_ATTRS: &str = "#8";
/// Attribute groups of the allocator functions (`runtime::Allocator`).
const ALLOCATOR_ATTRS: [(Allocator, &str); 3] = [
    (Allocator::Alloc, "#5"),
    (Allocator::Realloc, "#6"),
    (Allocator::Free, "#7"),
];

/// Intrinsic declarations requested while translating functions (deduplicated, sorted).
#[derive(Default)]
pub(crate) struct Intrinsics(BTreeSet<String>);

impl Intrinsics {
    /// Record that `declaration` (a full `declare ...` line) is needed.
    pub fn need(&mut self, declaration: String) {
        self.0.insert(declaration);
    }
}

/// How a function body is emitted into a module.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Definition {
    /// With its VIR linkage.
    Own,
    /// Defined here and referenced from other units: an internal function becomes `hidden`.
    Shared,
    /// A copy of another unit's function, for inlining only (`available_externally`).
    Import,
}

/// Print the whole program as one module.
pub(crate) fn emit_module(
    program: &vir::Program,
    target: &Target,
    optimized: bool,
) -> CodegenResult<String> {
    validate_aggregates(program)?;
    let unit = Unit {
        defines: (0..program.funcs.len()).collect(),
        statics: (0..program.statics.len()).collect(),
        ..Unit::default()
    };
    emit_unit(program, target, optimized, &unit, &Shared::default())
}

/// Print the module of one codegen unit; `shared`: which definitions other units refer to
/// (empty: none). The caller has checked the program's aggregates (`validate_aggregates`).
pub(crate) fn emit_unit(
    program: &vir::Program,
    target: &Target,
    optimized: bool,
    unit: &Unit,
    shared: &Shared,
) -> CodegenResult<String> {
    let mut out = String::new();
    let _ = writeln!(out, "; generated by velt_codegen_llvm");
    let _ = writeln!(out, "target triple = \"{}\"\n", target.triple);
    let own = unit.statics.iter().map(|&i| {
        let other_units = shared.statics.get(i).copied().unwrap_or(false);
        let how = if other_units {
            StaticDefinition::Shared
        } else {
            StaticDefinition::Own
        };
        (i, how)
    });
    let imported = unit
        .static_imports
        .iter()
        .map(|&i| (i, StaticDefinition::Import));
    for (i, how) in own.chain(imported) {
        let s = program
            .statics
            .get(i)
            .ok_or_else(|| format!("ICE: unit uses unknown static #{i}"))?;
        out.push_str(&static_data(
            program,
            i,
            s,
            how,
            target.wide_pointer_slots(),
        )?);
    }
    out.push('\n');
    out.push_str(&extern_declarations(program)?);
    for &i in &unit.declares {
        out.push_str(&function_declaration(program, i)?);
    }

    let mut intrinsics = Intrinsics::default();
    let mut debug = DebugInfo::new(program, optimized);
    let mut bodies = String::new();
    let wide = target.wide_pointer_slots();
    let own = unit.defines.iter().map(|&i| {
        let other_units = shared.funcs.get(i).copied().unwrap_or(false);
        let how = if other_units {
            Definition::Shared
        } else {
            Definition::Own
        };
        (i, how)
    });
    let imported = unit.imports.iter().map(|&i| (i, Definition::Import));
    for (i, how) in own.chain(imported) {
        let func = program
            .funcs
            .get(i)
            .ok_or_else(|| format!("ICE: unit defines unknown function #{i}"))?;
        let text = emit_function(program, func, how, &mut intrinsics, debug.as_mut(), wide)
            .map_err(|e| format!("codegen: in function `{}`: {e}", func.symbol))?;
        bodies.push('\n');
        bodies.push_str(&text);
    }
    for decl in &intrinsics.0 {
        let _ = writeln!(out, "{decl}");
    }
    out.push_str(&bodies);
    let _ = writeln!(
        out,
        "\nattributes {FN_ATTRS} = {{ {} }}",
        target.function_attributes().join(" ")
    );
    let _ = writeln!(out, "attributes {EXTERN_ATTRS} = {{ nounwind }}");
    let _ = writeln!(out, "attributes {NORETURN_ATTRS} = {{ noreturn nounwind }}");
    let _ = writeln!(
        out,
        "attributes {PURE_ATTRS} = {{ nounwind willreturn memory(none) }}"
    );
    let _ = writeln!(
        out,
        "attributes {READONLY_ATTRS} = {{ nounwind willreturn memory(read) }}"
    );
    // The caches live in runtime allocations compiled code never touches: inaccessible memory.
    let _ = writeln!(
        out,
        "attributes {READ_CACHING_ATTRS} = {{ nounwind willreturn memory(read, inaccessiblemem: readwrite) }}"
    );
    for (kind, group) in ALLOCATOR_ATTRS {
        let _ = writeln!(out, "attributes {group} = {{ {} }}", kind.function_attrs());
    }
    if let Some(debug) = debug {
        out.push_str(&debug.finish(target));
    }
    Ok(out)
}

/// One `declare` per distinct extern symbol not defined in this module.
fn extern_declarations(program: &vir::Program) -> CodegenResult<String> {
    let defined: HashSet<&str> = program.funcs.iter().map(|f| f.symbol.as_str()).collect();
    let mut declared = HashSet::new();
    let mut out = String::new();
    for e in &program.externs {
        if defined.contains(e.symbol.as_str()) || !declared.insert(e.symbol.as_str()) {
            continue;
        }
        let decl = match Allocator::of(&e.symbol, &e.params, e.ret) {
            Some(kind) => allocator_declaration(e, kind)?,
            None => plain_declaration(e)?,
        };
        out.push_str(&decl);
    }
    Ok(out)
}

/// `declare` line of a function another unit defines (with its parameter attributes, so calls
/// here are optimized as they would be in one module).
///
/// The function is linked into the same executable, so the declaration says so: without it LLVM
/// assumes the symbol may be preempted and calls it through the PLT and takes its address through
/// the GOT. An internal function shared between units is `hidden` in its unit, and is declared
/// `hidden` too. An exported one (`velt_main`) keeps default visibility, because the shared
/// runtime of debug builds looks it up by name (a hidden reference would hide the definition on
/// ELF), and is declared `dso_local` instead.
fn function_declaration(program: &vir::Program, index: usize) -> CodegenResult<String> {
    let func = program
        .funcs
        .get(index)
        .ok_or_else(|| format!("ICE: unit declares unknown function #{index}"))?;
    let linkage = match func.linkage {
        Linkage::Internal => "hidden",
        Linkage::Export => "dso_local",
    };
    let params = parameters(func, false)?;
    Ok(format!(
        "declare {linkage} {} {}({params}) {FN_ATTRS}\n",
        abi_ret(func.ret)?,
        global_name(&func.symbol)
    ))
}

/// `declare` line of an ordinary extern.
fn plain_declaration(e: &vir::ExternFn) -> CodegenResult<String> {
    let params = signature_params(&e.params)
        .map_err(|err| format!("codegen: extern `{}`: {err}", e.symbol))?;
    let attrs = match (e.noreturn, runtime::effects(&e.symbol)) {
        (true, _) => NORETURN_ATTRS,
        (false, Effects::None) => PURE_ATTRS,
        (false, Effects::ReadOnly) => READONLY_ATTRS,
        (false, Effects::ReadCaching) => READ_CACHING_ATTRS,
        (false, Effects::Any) => EXTERN_ATTRS,
    };
    Ok(format!(
        "declare {} {}({params}) {attrs}\n",
        abi_ret(e.ret)?,
        global_name(&e.symbol)
    ))
}

/// `declare` line of a runtime allocator function (see `runtime::Allocator`).
fn allocator_declaration(e: &vir::ExternFn, kind: Allocator) -> CodegenResult<String> {
    let mut params = Vec::with_capacity(e.params.len());
    for (i, &p) in e.params.iter().enumerate() {
        params.push(format!("{}{}", abi_type(p)?, kind.param_attrs(i)));
    }
    let group = ALLOCATOR_ATTRS
        .iter()
        .find(|(k, _)| *k == kind)
        .map_or(EXTERN_ATTRS, |(_, g)| g);
    Ok(format!(
        "declare {}{} {}({}) {group}\n",
        kind.return_attrs(),
        abi_ret(e.ret)?,
        global_name(&e.symbol),
        params.join(", ")
    ))
}

/// Comma-separated parameter types (for declarations).
fn signature_params(params: &[vir::Ty]) -> CodegenResult<String> {
    let parts: CodegenResult<Vec<String>> = params.iter().map(|&p| abi_type(p)).collect();
    Ok(parts?.join(", "))
}

/// Parameter list of a definition: `%p<i>` names plus the VIR param attributes
/// (vir.rs invariant 9) as LLVM parameter attributes.
pub(crate) fn definition_params(func: &vir::Function) -> CodegenResult<String> {
    parameters(func, true)
}

/// Parameter types with their attributes, and `%p<i>` names when `named`.
fn parameters(func: &vir::Function, named: bool) -> CodegenResult<String> {
    let mut parts = Vec::with_capacity(func.params.len());
    for (i, &p) in func.params.iter().enumerate() {
        let mut t = abi_type(p)?;
        let a = func.param_attr(i);
        if a.noalias {
            t.push_str(" noalias");
        }
        if a.readonly {
            t.push_str(" readonly");
        }
        if a.nonnull {
            t.push_str(" nonnull");
        }
        if a.dereferenceable > 0 {
            let _ = write!(t, " dereferenceable({})", a.dereferenceable);
        }
        if named {
            let _ = write!(t, " %p{i}");
        }
        parts.push(t);
    }
    Ok(parts.join(", "))
}

/// `define` line prefix for a function: linkage and return type. Functions shared between
/// units and imported copies are `hidden`: they never leave the executable.
pub(crate) fn define_prefix(func: &vir::Function, how: Definition) -> CodegenResult<String> {
    let linkage = match (func.linkage, how) {
        // Defined in the executable being linked, so calls need no PLT/GOT indirection.
        (Linkage::Export, Definition::Own | Definition::Shared) => "dso_local",
        (Linkage::Export, Definition::Import) => "available_externally dso_local",
        (Linkage::Internal, Definition::Own) => "internal",
        (Linkage::Internal, Definition::Shared) => "hidden",
        (Linkage::Internal, Definition::Import) => "available_externally hidden",
    };
    Ok(format!("define {linkage} {}", abi_ret(func.ret)?))
}
