//! Whole-program IR: header, statics (see `statics`), extern declarations, defined
//! functions, the intrinsics they use, and attribute groups.

use std::collections::{BTreeSet, HashSet};
use std::fmt::Write;

use velt_vir::vir::{self, Linkage};

use crate::debug::DebugInfo;
use crate::function::emit_function;
use crate::runtime::{self, Allocator, Effects};
use crate::statics::static_data;
use crate::target::Target;
use crate::types::{abi_ret, abi_type, global_name, validate_aggregates};
use crate::CodegenResult;

/// Attribute group of defined functions.
pub(crate) const FN_ATTRS: &str = "#0";
/// Attribute group of ordinary externs (C functions and the Rust runtime do not unwind into
/// Velt code: Rust `extern "C"` aborts on panic).
const EXTERN_ATTRS: &str = "#1";
/// Attribute group of noreturn externs.
const NORETURN_ATTRS: &str = "#2";
/// Attribute group of runtime functions that touch no memory (see `runtime`).
const PURE_ATTRS: &str = "#3";
/// Attribute group of runtime functions that only read memory.
const READONLY_ATTRS: &str = "#4";
/// Attribute groups of the allocator functions (`runtime::Allocator`).
const ALLOCATOR_ATTRS: [(Allocator, &str); 3] = [
    (Allocator::Alloc, "#5"),
    (Allocator::Realloc, "#6"),
    (Allocator::Free, "#7"),
];

/// Intrinsic declarations requested while translating functions (deduplicated, sorted).
#[derive(Default)]
pub(crate) struct Intrinsics(BTreeSet<String>);

impl Intrinsics {
    /// Record that `declaration` (a full `declare ...` line) is needed.
    pub fn need(&mut self, declaration: String) {
        self.0.insert(declaration);
    }
}

/// Print the whole module.
pub(crate) fn emit_module(
    program: &vir::Program,
    target: &Target,
    optimized: bool,
) -> CodegenResult<String> {
    validate_aggregates(program)?;
    let mut out = String::new();
    let _ = writeln!(out, "; generated by velt_codegen_llvm");
    let _ = writeln!(out, "target triple = \"{}\"\n", target.triple);
    for (i, s) in program.statics.iter().enumerate() {
        out.push_str(&static_data(program, i, s, target.wide_pointer_slots())?);
    }
    out.push('\n');
    out.push_str(&extern_declarations(program)?);

    let mut intrinsics = Intrinsics::default();
    let mut debug = DebugInfo::new(program, optimized);
    let mut bodies = String::new();
    for func in &program.funcs {
        let wide = target.wide_pointer_slots();
        let text = emit_function(program, func, &mut intrinsics, debug.as_mut(), wide)
            .map_err(|e| format!("codegen: in function `{}`: {e}", func.symbol))?;
        bodies.push('\n');
        bodies.push_str(&text);
    }
    for decl in &intrinsics.0 {
        let _ = writeln!(out, "{decl}");
    }
    out.push_str(&bodies);
    let _ = writeln!(
        out,
        "\nattributes {FN_ATTRS} = {{ {} }}",
        target.function_attributes().join(" ")
    );
    let _ = writeln!(out, "attributes {EXTERN_ATTRS} = {{ nounwind }}");
    let _ = writeln!(out, "attributes {NORETURN_ATTRS} = {{ noreturn nounwind }}");
    let _ = writeln!(
        out,
        "attributes {PURE_ATTRS} = {{ nounwind willreturn memory(none) }}"
    );
    let _ = writeln!(
        out,
        "attributes {READONLY_ATTRS} = {{ nounwind willreturn memory(read) }}"
    );
    for (kind, group) in ALLOCATOR_ATTRS {
        let _ = writeln!(out, "attributes {group} = {{ {} }}", kind.function_attrs());
    }
    if let Some(debug) = debug {
        out.push_str(&debug.finish(target));
    }
    Ok(out)
}

/// One `declare` per distinct extern symbol not defined in this module.
fn extern_declarations(program: &vir::Program) -> CodegenResult<String> {
    let defined: HashSet<&str> = program.funcs.iter().map(|f| f.symbol.as_str()).collect();
    let mut declared = HashSet::new();
    let mut out = String::new();
    for e in &program.externs {
        if defined.contains(e.symbol.as_str()) || !declared.insert(e.symbol.as_str()) {
            continue;
        }
        let decl = match Allocator::of(&e.symbol, &e.params, e.ret) {
            Some(kind) => allocator_declaration(e, kind)?,
            None => plain_declaration(e)?,
        };
        out.push_str(&decl);
    }
    Ok(out)
}

/// `declare` line of an ordinary extern.
fn plain_declaration(e: &vir::ExternFn) -> CodegenResult<String> {
    let params = signature_params(&e.params)
        .map_err(|err| format!("codegen: extern `{}`: {err}", e.symbol))?;
    let attrs = match (e.noreturn, runtime::effects(&e.symbol)) {
        (true, _) => NORETURN_ATTRS,
        (false, Effects::None) => PURE_ATTRS,
        (false, Effects::ReadOnly) => READONLY_ATTRS,
        (false, Effects::Any) => EXTERN_ATTRS,
    };
    Ok(format!(
        "declare {} {}({params}) {attrs}\n",
        abi_ret(e.ret)?,
        global_name(&e.symbol)
    ))
}

/// `declare` line of a runtime allocator function (see `runtime::Allocator`).
fn allocator_declaration(e: &vir::ExternFn, kind: Allocator) -> CodegenResult<String> {
    let mut params = Vec::with_capacity(e.params.len());
    for (i, &p) in e.params.iter().enumerate() {
        params.push(format!("{}{}", abi_type(p)?, kind.param_attrs(i)));
    }
    let group = ALLOCATOR_ATTRS
        .iter()
        .find(|(k, _)| *k == kind)
        .map_or(EXTERN_ATTRS, |(_, g)| g);
    Ok(format!(
        "declare {}{} {}({}) {group}\n",
        kind.return_attrs(),
        abi_ret(e.ret)?,
        global_name(&e.symbol),
        params.join(", ")
    ))
}

/// Comma-separated parameter types (for declarations).
fn signature_params(params: &[vir::Ty]) -> CodegenResult<String> {
    let parts: CodegenResult<Vec<String>> = params.iter().map(|&p| abi_type(p)).collect();
    Ok(parts?.join(", "))
}

/// Parameter list of a definition: `%p<i>` names plus the VIR param attributes
/// (vir.rs invariant 9) as LLVM parameter attributes.
pub(crate) fn definition_params(func: &vir::Function) -> CodegenResult<String> {
    let mut parts = Vec::with_capacity(func.params.len());
    for (i, &p) in func.params.iter().enumerate() {
        let mut t = abi_type(p)?;
        let a = func.param_attr(i);
        if a.noalias {
            t.push_str(" noalias");
        }
        if a.readonly {
            t.push_str(" readonly");
        }
        if a.nonnull {
            t.push_str(" nonnull");
        }
        if a.dereferenceable > 0 {
            let _ = write!(t, " dereferenceable({})", a.dereferenceable);
        }
        parts.push(format!("{t} %p{i}"));
    }
    Ok(parts.join(", "))
}

/// `define` line prefix for a function: linkage and return type.
pub(crate) fn define_prefix(func: &vir::Function) -> CodegenResult<String> {
    let linkage = match func.linkage {
        // Defined in the executable being linked, so calls need no PLT/GOT indirection.
        Linkage::Export => "dso_local",
        Linkage::Internal => "internal",
    };
    Ok(format!("define {linkage} {}", abi_ret(func.ret)?))
}
