//! Build script shared by `velt_rt` (the staticlib linked into programs), `velt_rt_host`
//! (the same sources as an rlib inside `velt`, for the `velt dev` JIT host) and `velt_rt_shared`
//! (the same sources as the shared library debug builds link):
//! - `velt_rt_host` gets `cfg(velt_rt_host)`, which drops the C `main` (the host has its own);
//! - `velt_rt_shared` gets `cfg(velt_rt_shared)`, which drops it too (the executable has its own);
//! - both get `$OUT_DIR/abi_symbols.rs`: every `#[no_mangle] extern "C"` function of the runtime
//!   as a `(name, address)` table, which the JIT registers so generated code can call the runtime.
//!   The addresses come from `extern "C"` declarations of the same symbols, so the table needs
//!   no module paths and keeps every function from being dead-stripped out of `velt`.

use std::path::{Path, PathBuf};

fn main() {
    println!("cargo::rustc-check-cfg=cfg(velt_rt_host)");
    println!("cargo::rustc-check-cfg=cfg(velt_rt_shared)");
    match std::env::var("CARGO_PKG_NAME").as_deref() {
        Ok("velt_rt_host") => println!("cargo::rustc-cfg=velt_rt_host"),
        Ok("velt_rt_shared") => println!("cargo::rustc-cfg=velt_rt_shared"),
        _ => {}
    }
    // Both packages build from crates/velt_rt/src.
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets it"));
    let src = manifest.join("../velt_rt/src");
    println!("cargo::rerun-if-changed={}", src.display());
    let mut names = vec![];
    collect(&src, &mut names);
    names.sort();
    names.dedup();
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets it"));
    std::fs::write(out.join("abi_symbols.rs"), render(&names)).expect("write abi_symbols.rs");
}

/// Exported function names in every `.rs` file under `dir` (tests excluded).
fn collect(dir: &Path, names: &mut Vec<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(&path, names);
        } else if path.extension().is_some_and(|e| e == "rs") {
            let text = std::fs::read_to_string(&path).unwrap_or_default();
            names.extend(exported_functions(&text));
        }
    }
}

/// `NAME` of each `#[no_mangle]` followed by `pub [unsafe] extern "C" fn NAME`. `main` is the
/// process entry, not part of the ABI the generated code calls.
fn exported_functions(text: &str) -> Vec<String> {
    let mut out = vec![];
    let mut pending = false;
    for line in text.lines().map(str::trim) {
        if line == "#[no_mangle]" {
            pending = true;
            continue;
        }
        if !pending || line.starts_with("#[") || line.starts_with("///") {
            continue;
        }
        pending = false;
        let Some((_, rest)) = line.split_once("extern \"C\" fn ") else {
            continue;
        };
        let name: String = rest
            .chars()
            .take_while(|c| c.is_alphanumeric() || *c == '_')
            .collect();
        if !name.is_empty() && name != "main" {
            out.push(name);
        }
    }
    out
}

fn render(names: &[String]) -> String {
    let mut s = String::from("// Generated by crates/velt_rt/build.rs.\nextern \"C\" {\n");
    for n in names {
        s.push_str(&format!("    fn {n}();\n"));
    }
    s.push_str("}\n\n/// Every runtime function generated code may call, by symbol name.\n");
    s.push_str(&format!(
        "pub static ABI_SYMBOLS: [(&str, AbiAddress); {}] = [\n",
        names.len()
    ));
    for n in names {
        s.push_str(&format!("    (\"{n}\", AbiAddress({n} as *const u8)),\n"));
    }
    s.push_str("];\n");
    s
}
