//! The generated test harness and reading its output.
//!
//! For `math.test.vlt` the harness is a root module (virtual file next to it) like
//! ```text
//! import { test_add, test_sub } from "./math.test";
//! function main() {
//!   test_add();
//!   console.log("::velt-test-ok:: test_add");
//!   ...
//! }
//! ```
//! When any test is `async`, `main` is `async` and awaits those tests.
//! A failing `assert` panics (or a test throws), which ends the process: the test after the last
//! marker line is the one that failed. The runner then rebuilds a harness for the remaining tests,
//! so one failure does not hide the others.

/// Prefix of the line the harness prints after each passing test.
pub const OK_MARKER: &str = "::velt-test-ok:: ";

/// Velt source of a harness running `tests` (imported from `import_spec`) in order; those in
/// `async_tests` are awaited.
pub fn harness_source(import_spec: &str, tests: &[String], async_tests: &[String]) -> String {
    let mut src = String::from("// Generated by `velt test`.\n");
    src.push_str(&format!(
        "import {{ {} }} from \"{import_spec}\";\n\n",
        tests.join(", ")
    ));
    let any_async = tests.iter().any(|t| async_tests.contains(t));
    src.push_str(if any_async {
        "async function main() {\n"
    } else {
        "function main() {\n"
    });
    for t in tests {
        let call = if async_tests.contains(t) {
            "await "
        } else {
            ""
        };
        src.push_str(&format!(
            "  {call}{t}();\n  console.log(\"{OK_MARKER}{t}\");\n"
        ));
    }
    src.push_str("}\n");
    src
}

/// One harness run, read back.
#[derive(Debug, PartialEq, Eq)]
pub struct RunOutput {
    /// How many of the tests (a prefix of the list) passed.
    pub passed: usize,
    /// Stdout with marker lines replaced by `ok <name>` (test output stays interleaved).
    pub display: Vec<String>,
}

/// Interpret harness stdout for `tests` (in harness order).
pub fn read_output(stdout: &str, tests: &[String]) -> RunOutput {
    let mut passed = 0;
    let mut display = vec![];
    for line in stdout.lines() {
        match line.strip_prefix(OK_MARKER) {
            Some(name) if tests.get(passed).is_some_and(|t| t == name) => {
                passed += 1;
                display.push(format!("ok {name}"));
            }
            _ => display.push(line.to_string()),
        }
    }
    RunOutput { passed, display }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn names(n: &[&str]) -> Vec<String> {
        n.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn generates_imports_and_calls_in_order() {
        let src = harness_source("./math.test", &names(&["test_add", "test_sub"]), &[]);
        assert!(
            src.contains("import { test_add, test_sub } from \"./math.test\";"),
            "{src}"
        );
        let add = src.find("test_add();").unwrap();
        let sub = src.find("test_sub();").unwrap();
        assert!(add < sub);
        assert!(src.contains("console.log(\"::velt-test-ok:: test_add\");"));
        assert!(src.contains("\nfunction main()"));
    }

    #[test]
    fn awaits_async_tests() {
        let src = harness_source(
            "./x.test",
            &names(&["test_a", "test_b"]),
            &names(&["test_b"]),
        );
        assert!(src.contains("async function main()"), "{src}");
        assert!(
            src.contains("  test_a();") && src.contains("  await test_b();"),
            "{src}"
        );
    }

    #[test]
    fn harness_parses() {
        let src = harness_source("./x.test", &names(&["test_a"]), &names(&["test_a"]));
        let (_, diags) = velt_syntax::parse_file(velt_common::FileId(0), &src);
        assert!(diags.is_empty(), "{diags:?}");
    }

    #[test]
    fn reads_markers_and_keeps_test_output() {
        let tests = names(&["test_a", "test_b", "test_c"]);
        let out = read_output("hello\n::velt-test-ok:: test_a\nfrom b\n", &tests);
        assert_eq!(out.passed, 1);
        assert_eq!(out.display, ["hello", "ok test_a", "from b"]);
        // A stray marker for the wrong test is just output.
        assert_eq!(read_output("::velt-test-ok:: test_c\n", &tests).passed, 0);
    }
}
