//! The runtime functions lowering calls (`docs/internals/contracts/rt_abi.md`) and their VIR
//! signatures. M2 additions (hash, math, refcounts) and the M3/M4 functions (futures, tasks,
//! atomics, mutex, string builder, JSON reader) are in `docs/internals/contracts/rt_abi_async.md`.

use crate::vir::Ty;

/// A `velt_rt` function used by lowering.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum Rt {
    StrConcat,
    StrAppend,
    StrFromI64,
    StrFromU64,
    StrFromF64,
    StrFromBool,
    StrClone,
    StrOwn,
    StrDrop,
    StrCmp,
    /// `charCodeAt` on a non-ASCII string (ASCII is read inline).
    StrCharCodeAt,
    WriteStr,
    WriteI64,
    WriteU64,
    WriteF64,
    WriteBool,
    WriteByte,
    Panic,
    Exit,
    /// Source location bookkeeping for uncaught-error reports (`lower_with` only).
    SetThrowLoc,
    ThrowLoc,
    PowF64,
    PowI64,
    Alloc,
    Realloc,
    Free,
    StrHash,
    Sqrt,
    Floor,
    Ceil,
    Round,
    Trunc,
    FAbs,
    RcInc,
    RcDec,
    DropState,
    DropQueue,
    DropDrain,
    // M3: futures and tasks (rt_abi_async.md §1, §2, §8, §9)
    FutPoll,
    FutDrop,
    FutPeek,
    FutBox,
    FutStart,
    FutDetach,
    FutTransfer,
    XferBegin,
    XferEnd,
    XferFind,
    XferRecord,
    XferDefer,
    XferSuspend,
    XferResume,
    CopyLock,
    CopyUnlock,
    SawCells,
    TakeCells,
    FutsHandled,
    Race,
    RaceOk,
    YieldNow,
    YieldNowFut,
    Sleep,
    All,
    AllWithDrop,
    AllOrReject,
    ChanSend,
    ChanReceive,
    ChanTrySend,
    ChanTryReceive,
    BlockOn,
    Spawn,
    SpawnTransfer,
    SpawnFut,
    PerfNow,
    DateNow,
    AtomicAdd,
    AtomicLoad,
    AtomicStore,
    MutexInit,
    MutexLock,
    MutexUnlock,
    // M4: string builder and JSON pull reader (rt_abi_async.md §12)
    StrEq,
    StrbufNew,
    /// A template literal's builder made from a fresh part's buffer (`build_sized`).
    StrbufAdopt,
    StrbufPushStr,
    StrbufPushBytes,
    StrbufPushI64,
    StrbufPushU64,
    StrbufInspectBegin,
    StrbufInspectEnter,
    StrbufInspectLeave,
    StrbufInspectCircular,
    StrbufInspectAtom,
    StrbufInspectMore,
    StrbufLen,
    StrbufInspectLayout,
    JsonEnter,
    JsonLeave,
    StrbufPushF64,
    StrbufPushInspectF64,
    StrbufPushJsonF64,
    StrbufPushBool,
    StrbufPushByte,
    StrbufPushJsonStr,
    StrbufPushInspectStr,
    StrbufPushInspectKey,
    StrbufPushJsonValue,
    StrbufPushInspectJson,
    StrbufFinish,
    StrbufDrop,
    JsonReaderNewWith,
    JsonSkipUnknown,
    JsonReaderFree,
    JsonPeek,
    JsonObjectStart,
    JsonNextKey,
    JsonArrayStart,
    JsonArrayNext,
    JsonReadString,
    JsonReadF64,
    JsonReadI64,
    JsonReadBool,
    JsonReadNull,
    JsonSkipValue,
    JsonSkipLookahead,
    JsonReadValue,
    JsonMark,
    JsonReset,
    JsonEnd,
    JsonError,
}

impl Rt {
    /// (symbol, params, ret, noreturn). `bool` is passed as VIR `Bool` (one byte, 0/1 — rt's `u8`).
    pub(super) fn sig(self) -> (&'static str, Vec<Ty>, Ty, bool) {
        use Ty::*;
        let math = |s| (s, vec![F64], F64, false);
        match self {
            Rt::StrConcat => ("velt_rt_str_concat", vec![Ptr, Ptr, Ptr], Unit, false),
            Rt::StrAppend => ("velt_rt_str_append", vec![Ptr, Ptr], Unit, false),
            Rt::StrFromI64 => ("velt_rt_str_from_i64", vec![I64, Ptr], Unit, false),
            Rt::StrFromU64 => ("velt_rt_str_from_u64", vec![U64, Ptr], Unit, false),
            Rt::StrFromF64 => ("velt_rt_str_from_f64", vec![F64, Ptr], Unit, false),
            Rt::StrFromBool => ("velt_rt_str_from_bool", vec![Bool, Ptr], Unit, false),
            Rt::StrClone => ("velt_rt_str_clone", vec![Ptr, Ptr], Unit, false),
            Rt::StrOwn => ("velt_rt_str_own", vec![Ptr, Ptr], Unit, false),
            Rt::StrDrop => ("velt_rt_str_drop", vec![Ptr], Unit, false),
            Rt::StrCmp => ("velt_rt_str_cmp", vec![Ptr, Ptr], I32, false),
            Rt::StrCharCodeAt => ("velt_rt_str_char_code_at", vec![Ptr, I64], I64, false),
            Rt::WriteStr => ("velt_rt_write_str", vec![U32, Ptr], Unit, false),
            Rt::WriteI64 => ("velt_rt_write_i64", vec![U32, I64], Unit, false),
            Rt::WriteU64 => ("velt_rt_write_u64", vec![U32, U64], Unit, false),
            Rt::WriteF64 => ("velt_rt_write_f64", vec![U32, F64], Unit, false),
            Rt::WriteBool => ("velt_rt_write_bool", vec![U32, Bool], Unit, false),
            Rt::WriteByte => ("velt_rt_write_byte", vec![U32, U8], Unit, false),
            Rt::Panic => ("velt_rt_panic", vec![Ptr], Unit, true),
            Rt::Exit => ("velt_rt_exit", vec![I32], Unit, true),
            Rt::SetThrowLoc => ("velt_rt_set_throw_loc", vec![Ptr], Unit, false),
            Rt::ThrowLoc => ("velt_rt_throw_loc", vec![], Ptr, false),
            Rt::PowF64 => ("velt_rt_pow_f64", vec![F64, F64], F64, false),
            Rt::PowI64 => ("velt_rt_pow_i64", vec![I64, I64], I64, false),
            Rt::Alloc => ("velt_rt_alloc", vec![U64, U64], Ptr, false),
            Rt::Realloc => ("velt_rt_realloc", vec![Ptr, U64, U64, U64], Ptr, false),
            Rt::Free => ("velt_rt_free", vec![Ptr, U64, U64], Unit, false),
            Rt::StrHash => ("velt_rt_str_hash", vec![Ptr], U64, false),
            Rt::Sqrt => math("velt_rt_math_sqrt"),
            Rt::Floor => math("velt_rt_math_floor"),
            Rt::Ceil => math("velt_rt_math_ceil"),
            Rt::Round => math("velt_rt_math_round"),
            Rt::Trunc => math("velt_rt_math_trunc"),
            Rt::FAbs => math("velt_rt_math_fabs"),
            Rt::RcInc => ("velt_rt_rc_inc", vec![Ptr], Unit, false),
            Rt::RcDec => ("velt_rt_rc_dec", vec![Ptr], U8, false),
            Rt::DropState => ("velt_rt_drop_state", vec![], Ptr, false),
            Rt::DropQueue => ("velt_rt_drop_queue", vec![Ptr, Ptr], Unit, false),
            Rt::DropDrain => ("velt_rt_drop_drain", vec![], Unit, false),
            _ => self.sig_m3(),
        }
    }

    /// Signatures of the M3/M4 functions.
    fn sig_m3(self) -> (&'static str, Vec<Ty>, Ty, bool) {
        use Ty::*;
        let f = |s, params, ret| (s, params, ret, false);
        match self {
            Rt::FutPoll => f("velt_rt_fut_poll", vec![Ptr, Ptr], U32),
            Rt::FutDrop => f("velt_rt_fut_drop", vec![Ptr], Unit),
            Rt::FutPeek => f("velt_rt_fut_peek", vec![Ptr], U8),
            Rt::FutBox => f("velt_rt_fut_box", vec![Ptr, Ptr, Ptr, U64, U64], Ptr),
            Rt::FutStart => f("velt_rt_fut_start", vec![Ptr, Ptr], Unit),
            Rt::FutDetach => f("velt_rt_fut_detach", vec![Ptr, Ptr], Unit),
            Rt::FutTransfer => f("velt_rt_fut_transfer", vec![Ptr, Ptr], Unit),
            Rt::XferBegin => f("velt_rt_xfer_begin", vec![], Unit),
            Rt::XferEnd => f("velt_rt_xfer_end", vec![], Unit),
            Rt::XferFind => f("velt_rt_xfer_find", vec![Ptr], Ptr),
            Rt::XferRecord => f("velt_rt_xfer_record", vec![Ptr, Ptr], Unit),
            Rt::XferDefer => f("velt_rt_xfer_defer", vec![Ptr, Ptr], U8),
            Rt::XferSuspend => f("velt_rt_xfer_suspend", vec![], U32),
            Rt::XferResume => f("velt_rt_xfer_resume", vec![U32], Unit),
            Rt::CopyLock => f("velt_rt_copy_lock", vec![], Unit),
            Rt::CopyUnlock => f("velt_rt_copy_unlock", vec![], Unit),
            Rt::SawCells => f("velt_rt_saw_cells", vec![], Unit),
            Rt::TakeCells => f("velt_rt_take_cells", vec![], U8),
            Rt::FutsHandled => f("velt_rt_futs_handled", vec![Ptr, U64, Ptr], Unit),
            Rt::Race => f("velt_rt_race", vec![Ptr, U64, U64], Ptr),
            Rt::RaceOk => f("velt_rt_race_ok", vec![Ptr, U64, U64, Ptr], Ptr),
            Rt::YieldNow => f("velt_rt_yield_now", vec![Ptr], Unit),
            Rt::YieldNowFut => f("velt_rt_yield_now_fut", vec![], Ptr),
            Rt::Sleep => f("velt_rt_sleep", vec![I64], Ptr),
            Rt::All => f("velt_rt_all", vec![Ptr, U64, U64, Ptr], Ptr),
            Rt::AllWithDrop => f("velt_rt_all_with_drop", vec![Ptr, U64, U64, Ptr, Ptr], Ptr),
            Rt::AllOrReject => f("velt_rt_all_or_reject", vec![Ptr, U64, U64, Ptr, Ptr], Ptr),
            Rt::ChanSend => f("velt_rt_chan_send", vec![U64, Ptr, U64, Ptr], Ptr),
            Rt::ChanReceive => f("velt_rt_chan_receive", vec![U64, U64, U64, U64], Ptr),
            Rt::ChanTrySend => f("velt_rt_chan_try_send", vec![U64, Ptr, U64, Ptr], Bool),
            Rt::ChanTryReceive => f("velt_rt_chan_try_receive", vec![U64, Ptr, U64, U64], Unit),
            Rt::BlockOn => f("velt_rt_block_on", vec![Ptr, Ptr], Unit),
            Rt::Spawn => f(
                "velt_rt_spawn",
                vec![Ptr, Ptr, Ptr, U64, U64, U64, Ptr],
                Ptr,
            ),
            Rt::SpawnTransfer => f(
                "velt_rt_spawn_transfer",
                vec![Ptr, Ptr, Ptr, U64, U64, U64, Ptr, Ptr],
                Ptr,
            ),
            Rt::SpawnFut => f("velt_rt_spawn_fut", vec![Ptr, U64, Ptr], Ptr),
            Rt::PerfNow => f("velt_rt_perf_now", vec![], F64),
            Rt::DateNow => f("velt_rt_date_now", vec![], I64),
            Rt::AtomicAdd => f("velt_rt_atomic_add_i64", vec![Ptr, I64], I64),
            Rt::AtomicLoad => f("velt_rt_atomic_load_i64", vec![Ptr], I64),
            Rt::AtomicStore => f("velt_rt_atomic_store_i64", vec![Ptr, I64], Unit),
            Rt::MutexInit => f("velt_rt_mutex_init", vec![Ptr], Unit),
            Rt::MutexLock => f("velt_rt_mutex_lock", vec![Ptr], Unit),
            Rt::MutexUnlock => f("velt_rt_mutex_unlock", vec![Ptr], Unit),
            _ => self.sig_json(),
        }
    }

    /// Signatures of the string builder and JSON reader functions.
    fn sig_json(self) -> (&'static str, Vec<Ty>, Ty, bool) {
        use Ty::*;
        let f = |s, params, ret| (s, params, ret, false);
        match self {
            Rt::StrEq => f("velt_rt_str_eq", vec![Ptr, Ptr], U8),
            Rt::StrbufNew => f("velt_rt_strbuf_new", vec![U64, Ptr], Unit),
            Rt::StrbufAdopt => f("velt_rt_strbuf_adopt", vec![Ptr, Ptr, U64, Ptr], U8),
            Rt::StrbufPushStr => f("velt_rt_strbuf_push_str", vec![Ptr, Ptr], Unit),
            Rt::StrbufPushBytes => f("velt_rt_strbuf_push_bytes", vec![Ptr, Ptr, U64], Unit),
            Rt::StrbufPushI64 => f("velt_rt_strbuf_push_i64", vec![Ptr, I64], Unit),
            Rt::StrbufPushU64 => f("velt_rt_strbuf_push_u64", vec![Ptr, U64], Unit),
            Rt::StrbufInspectBegin => f("velt_rt_strbuf_inspect_begin", vec![], Unit),
            Rt::StrbufInspectEnter => f("velt_rt_strbuf_inspect_enter", vec![Ptr, Ptr], U8),
            Rt::StrbufInspectLeave => f("velt_rt_strbuf_inspect_leave", vec![Ptr], Unit),
            Rt::StrbufInspectCircular => f("velt_rt_strbuf_inspect_circular", vec![Ptr, Ptr], U8),
            Rt::StrbufInspectAtom => f("velt_rt_strbuf_inspect_atom", vec![Ptr, U64], Unit),
            Rt::StrbufInspectMore => f("velt_rt_strbuf_inspect_more", vec![Ptr, U64], Unit),
            Rt::StrbufLen => f("velt_rt_strbuf_len", vec![Ptr], U64),
            Rt::StrbufInspectLayout => f("velt_rt_strbuf_inspect_layout", vec![Ptr, U64], Unit),
            Rt::JsonEnter => f("velt_rt_json_enter", vec![Ptr], U8),
            Rt::JsonLeave => f("velt_rt_json_leave", vec![], Unit),
            Rt::StrbufPushF64 => f("velt_rt_strbuf_push_f64", vec![Ptr, F64], Unit),
            Rt::StrbufPushInspectF64 => f("velt_rt_strbuf_push_inspect_f64", vec![Ptr, F64], Unit),
            Rt::StrbufPushJsonF64 => f("velt_rt_strbuf_push_json_f64", vec![Ptr, F64], Unit),
            Rt::StrbufPushBool => f("velt_rt_strbuf_push_bool", vec![Ptr, Bool], Unit),
            Rt::StrbufPushByte => f("velt_rt_strbuf_push_byte", vec![Ptr, U8], Unit),
            Rt::StrbufPushJsonStr => f("velt_rt_strbuf_push_json_str", vec![Ptr, Ptr], Unit),
            Rt::StrbufPushInspectStr => f("velt_rt_strbuf_push_inspect_str", vec![Ptr, Ptr], Unit),
            Rt::StrbufPushInspectKey => f("velt_rt_strbuf_push_inspect_key", vec![Ptr, Ptr], Unit),
            Rt::StrbufPushJsonValue => f("velt_rt_strbuf_push_json_value", vec![Ptr, Ptr], Unit),
            Rt::StrbufPushInspectJson => f(
                "velt_rt_strbuf_push_inspect_json",
                vec![Ptr, Ptr, U8, U32],
                Unit,
            ),
            Rt::StrbufFinish => f("velt_rt_strbuf_finish", vec![Ptr, Ptr], Unit),
            Rt::StrbufDrop => f("velt_rt_strbuf_drop", vec![Ptr], Unit),
            Rt::JsonReaderNewWith => f("velt_rt_json_reader_new_with", vec![Ptr, U32, U32], Ptr),
            Rt::JsonSkipUnknown => f("velt_rt_json_reader_skip_unknown", vec![Ptr], U8),
            Rt::JsonReaderFree => f("velt_rt_json_reader_free", vec![Ptr], Unit),
            Rt::JsonPeek => f("velt_rt_json_reader_peek", vec![Ptr], U32),
            Rt::JsonObjectStart => f("velt_rt_json_reader_expect_object_start", vec![Ptr], U8),
            Rt::JsonNextKey => f("velt_rt_json_reader_next_key", vec![Ptr, Ptr], U8),
            Rt::JsonArrayStart => f("velt_rt_json_reader_expect_array_start", vec![Ptr], U8),
            Rt::JsonArrayNext => f("velt_rt_json_reader_array_next", vec![Ptr], U8),
            Rt::JsonReadString => f("velt_rt_json_reader_read_string", vec![Ptr, Ptr], U8),
            Rt::JsonReadF64 => f("velt_rt_json_reader_read_f64", vec![Ptr, Ptr], U8),
            Rt::JsonReadI64 => f("velt_rt_json_reader_read_i64", vec![Ptr, Ptr], U8),
            Rt::JsonReadBool => f("velt_rt_json_reader_read_bool", vec![Ptr, Ptr], U8),
            Rt::JsonReadNull => f("velt_rt_json_reader_read_null", vec![Ptr], U8),
            Rt::JsonSkipValue => f("velt_rt_json_reader_skip_value", vec![Ptr], U8),
            Rt::JsonSkipLookahead => f("velt_rt_json_reader_skip_lookahead", vec![Ptr], U8),
            Rt::JsonReadValue => f("velt_rt_json_reader_read_value", vec![Ptr, Ptr], U8),
            Rt::JsonMark => f("velt_rt_json_reader_mark", vec![Ptr], U64),
            Rt::JsonReset => f("velt_rt_json_reader_reset", vec![Ptr, U64], Unit),
            Rt::JsonEnd => f("velt_rt_json_reader_end", vec![Ptr], U8),
            Rt::JsonError => f("velt_rt_json_error", vec![Ptr, Ptr, Ptr, Ptr], Unit),
            other => crate::lower::ice(format_args!("no signature for {other:?}")),
        }
    }
}
